GAME_NAME_LIST = {
    "code_golf_game"  : "Code Golf",
    "chameleon_game"  : "Octocat-ch Game",
    "trivia_game"     : "Trivia Game",
    "chart_game"      : "Participant Data",
}

GAME_DESCRIPTION_LIST = {
    "code_golf_game"  : "Solve the challenge in the fewsest number of characters.",
    "chameleon_game"  : "Click the Octocat as many times as you can.",
    "trivia_game"     : "Solve these trivia questions.",
    "chart_game"      : "Look at these cool statistics.",
}

GAME_LINK_LIST = {
    "code_golf_game"  : "/play/code-golf_game",
    "chameleon_game"  : "/play/chameleon_game",
    "trivia_game"     : "/play/trivia_game",
    "chart_game"      : "/play/chart_game",
}

TRIVIA_QUESTIONS_LIST = {
    1 : "What is 4+5",
    2 : "What is 1+9",
    3 : "What is 1*5",
    4 : "Andrew, or Andrew?",
    5 : "What is a state located in the southeastern region of the United States?",
    6 : "What is a U.S. state situated in the northwest extremity of the Americas?",
    7 : "What is a state in the southwestern region of the United States?",
    8 : "What is a state located in the southeastern region of the United States?",
    9 : "What is the most populous state in the United States as well as the third most extensive by area?",
    10 : "What is a state in the United States encompassing most of the Southern Rocky Mountains as well as the northeastern portion of the Colorado Plateau and the western edge of the Great Plains?",
    11 : "What is the southernmost state in the New England region of the United States?",
    12 : "What is one of the Mid-Atlantic states located in the Northeast megalopolis region of the United States?",
    13 : "What is a state located in the southeastern region of the United States?",
    15 : "What is the 50th and most recent state of the United States of America, receiving statehood on August 21, 1959?",
    16 : "What is a state in the northwestern region of the United States?",
    17 : "What is a state in the midwestern region of the United States?",
    18 : "What is a U.S. state located in the midwestern and Great Lakes regions of North America?",
    19 : "What is a U.S. state in the Midwestern United States, bordered by the Mississippi River on the east and the Missouri River and the Big Sioux River on the west?",
    20 : "What is a U.S. state located in the Midwestern United States?",
    21 : "What is a state located in the east south-central region of the United States?",
    22 : "What is a state located in the southern region of the United States?",
    23 : "What is a state in New England, in the United States?",
    24 : "What is a state located in the Mid-Atlantic region of the United States, bordering Virginia, West Virginia, and Washington, D.C. to its south and west; Pennsylvania to its north; "\
		 "and Delaware to its east?",
    25 : "What is the most populous state in the New England part of the northeastern region of the United States?",
    26 : "What is a state located in the Great Lakes and midwestern regions of the United States?",
    27 : "What is a state in the Midwestern United States?",
    28 : "What is a state located in the southern region of the United States?",
    29 : "What is a state located in the Midwestern United States?",
    30 : "What is a state in the Western region of the United States?",
    31 : "What is a state that lies in both the Great Plains and the Midwestern United States?",
    32 : "What is a state in the Western, Mountain West, and Southwestern regions of the United States of America?",
    33 : "What is a state in the New England region of the northeastern United States?",
    34 : "What is a state in the northeastern and mid-Atlantic regions of the United States?",
    35 : "What is a state located in the southwestern region of the United States of America?",
    36 : "What is a state in the Northeastern United States and is the 27th-most extensive, fourth-most populous, and seventh-most densely populated U.S. state?",
    37 : "What is a state in the southeastern region of the United States?",
    38 : "What is the 39th state of the United States, having been admitted to the union on November 2, 1889?",
    39 : "What is an Eastern state in the Great Lakes region of the United States?",
    40 : "What is a state located in the South Central United States?",
    41 : "What is a state in the Pacific Northwest region of the United States?",
    42 : "What is a state located in the northern and Mid-Atlantic regions of the United States?",
    43 : "What is a state in the New England region of the United States?",
    44 : "What is a state in the southeastern region of the United States?",
    45 : "What is a state located in the Midwestern region of the United States?",
    46 : "What is a state located in the southeastern region of the United States?",
    47 : "What is the second largest state in the United States by both area and population?",
    48 : "What is a state in the western United States?",
    49 : "What is a New England state in the northeastern region of the United States?",
    50 : "What is a state located in the South Atlantic region of the United States?",
    52 : "What is a state located in the Appalachian region of the Southern United States?",
    53 : "What is a U.S. state located in the north-central United States, in the Midwest and Great Lakes regions?",
    54 : "What is a state in the mountain region of the Western United States?",
}

TRIVIA_ANSWERS_LIST = {
    1 : "9",
    2 : "10",
    3 : "5",
    4: "yoonko",
    5 : "Alabama",
    6 : "Alaska",
    7 : "Arizona",
    8 : "Arkansas",
    9 : "California",
    10 : "Colorado",
    11 : "Connecticut",
    12 : "Delaware",
    13 : "Florida",
    15 : "Hawaii",
    16 : "Idaho",
    17 : "Illinois",
    18 : "Indiana",
    19 : "Iowa",
    20 : "Kansas",
    21 : "Kentucky",
    22 : "Louisiana",
    23 : "Maine",
    24 : "Maryland",
    25 : "Massachusetts",
    26 : "Michigan",
    27 : "Minnesota",
    28 : "Mississippi",
    29 : "Missouri",
    30 : "Montana",
    31 : "Nebraska",
    32 : "Nevada",
    33 : "New Hampshire",
    34 : "New Jersey",
    35 : "New Mexico",
    36 : "New York",
    37 : "North Carolina",
    38 : "North Dakota",
    39 : "Ohio",
    40 : "Oklahoma",
    41 : "Oregon",
    42 : "Pennsylvania",
    43 : "Rhode Island",
    44 : "South Carolina",
    45 : "South Dakota",
    46 : "Tennessee",
    47 : "Texas",
    48 : "Utah",
    49 : "Vermont",
    50 : "Virginia",
    52 : "West Virginia",
    53 : "Wisconsin",
    54 : "Wyoming",
}

CODE_GOLF_QUESTIONS_LIST = {
    "1" : "Write a function to multiply a number by 10",
    "2" : "Write a function to multiply a number by 5",
	"3" : "Write a single line of Python code that will return a newline character.",
	"4" : "Write a line of Python code which will add 10 to a number.",
	"5" : "Join a list of strings into a single string, with each string separated from the next in the list by a single space character.",
	"6" : "Create a list which is equal to the first 5 elements of the input list.",
	"7" : "Write a boolean expression that tests whether a variable containing a python string has a vowel.",
	"8" : "Write Python code which, when executed, changes a string with lowercase letters so that it's now uppercase and in reversed order."
}

CODE_GOLF_ANSWERS_LIST = {
    "1" : {"inputs": [0, 1, 2, 10], "outputs": [0, 10, 20, 100]},
    "2" : {"inputs": [0, 1, 2, 10], "outputs": [0, 5, 10, 50]},
	"3" : {"inputs": ['', '', '', ''], "outputs": ['\n', '\n', '\n', '\n']},
    "4" : {"inputs": [0, 1, 2, 10], "outputs": [10, 11, 12, 20]},
    "5" : {"inputs": [['a', 'b', 'c'], ['a b c'],[]], "outputs": ['a b c', 'a b c', '']},
    "6" : {"inputs": [[0, 1, 2, 3, 4, 5, 6]], "outputs": [[0, 1, 2, 3, 4]]},
    "7" : {"inputs": ['"ab"', '"ef"', '"ig"', '"op"', '"uv"', '"bfgpv"','""'], "outputs": [True, True, True, True, True, False, False]},
    "8" : {"inputs": ['""', '"a"', '"abc"'], "outputs": ['', 'A', 'CBA']}
}
USER_TO_PASS_LIST = {
    "Robert" : "robert",
    "Advith" : "advith",
    "Anne"   : "anne",
    "Chen"   : "chen"
}

COMMON_WORD_LIST_NOUN = ["dog", "cat", "frog", "pizza", "pie", "bed"]
COMMON_WORD_LIST_VERB = ["eat", "slap", "hug", "watch"]
COMMON_NUMBER_LIST = ["1", "2", "3", "4", "5"]
