GAME_NAME_LIST = {
    "code_golf_game"  : "Code Golf",
    "chameleon_game"  : "Chameleon Game",
    "trivia_game"     : "Trivia Game",
    "chart_game"      : "Participant Data",
}

GAME_DESCRIPTION_LIST = {
    "code_golf_game"  : "Solve the challenge in the fewsest number of characters.",
    "chameleon_game"  : "Click the chameleon as many times as you can.",
    "trivia_game"     : "Solve these trivia questions.",
    "chart_game"      : "This isn't even a game. Bruh. pls.",
}

GAME_LINK_LIST = {
    "code_golf_game"  : "/play/code-golf_game",
    "chameleon_game"  : "/play/chameleon_game",
    "trivia_game"     : "/play/trivia_game",
    "chart_game"      : "/play/chart_game",
}

TRIVIA_QUESTIONS_LIST = {
    1 : "Which southeastern state in the United States has one of the nation's largest navigable waterways?",
    2 : "What is a U.S. state situated in the northwest extremity of the Americas?",
    3 : "Which southwestern state in the United States had part of its territory bought in 1853 as part of the Gadsden Purchase?",
    4 : "Which southeastern state in the United States contains parts of the Ozark and Ouachita Mountains?",
    5 : "Which state was admitted into the union in 1850 and is the birthplace of the film industry?",
    6 : "Whisk Four Corners state contains the peak of Mount Elbert?",
    7 : "Which northeastern state contains the Thames River as has Yankee Doodle as their state song?",
    8 : "A famous photograph of George Washington crossing a river on Christmas Day takes place in which state?",
    9 : "The Seminole Wars occurred in which state that borders the Gulf of Mexico?",
    10 : "Which southeastern state is also known as The Peach State?",
    11 : "Which state is primarily formed from volcanic activity?",
    12 : "Which northwestern state contains parts of the Great Basin, Snake River Plain, and Rocky Mountains?",
    13 : "Which midwestern US state contains the Erie Canal?",
    14 : "Which midwestern US state is also known as 'Land of the Indians'?",
    15 : "Which midwestern US state is bordered by the Mississippi River on the east and the Missouri River and the Big Sioux River on the west?",
    16 : "Which US state is Dorothy in 'The Wizard of Oz' from?",
    17 : "Which south-central US state is known for their nationally successful fast food chain?",
    18 : "Which US state is named in a land purchase between America and the French in 1803?",
    19 : "Which northeastern US state was admitted into the Union as part of the Missouri Compromise?",
    20 : "Which midatlantic US state borders Virginia and is known as the birthplace of religious freedom?",
    21 : "Which northeastern US state is well known for their higher education, engineering, and maritime trade?",
    22 : "Which US state is bounded by four Great Lakes?",
    23 : "Which midwestern US state contains the Metrodome?",
    24 : "Which southern US state carries the reputation of being the most religious state in the country?",
    25 : "Which midwest US state once held the starting points of the Pony Express, Santa Fe Trail, and Oregon Trail?",
    26 : "Which western US state has a landsize in the top 5 of all US states, but a population density in the bottom 5 of all US states?",
    27 : "Which midwestern US state is divided into the Dissected Till Plains and the Great Plains?",
    28 : "In which midwestern US state is prostitution legal?",
    29 : "Which northeastern US state contains the cities Manchester and Concord?",
    30 : "Which northeastern US state is known as the car theft capital of the world?",
    31 : "Which Four Corners state was named by Spanish explorers seeking the wealth of Mexico?",
    32 : "Which northeastern US state as 722 miles of subway track?",
    33 : "Which western US state contains Harker's Island?",
    34 : "Which northern US state grows omre sunflowers than any other state?",
    35 : "Which eastern state is also known as the Buckeye State?",
    36 : "Which south-central US state contains the Ouachitas, Arbuckles, Wichitas, and Kiamichis mountain ranges?",
    37 : "Which Pacific northwest state contains Crater Lake?",
    38 : "In which US state was the Hershey company founded in?",
    39 : "What is the smallest state in the United States?",
    40 : "In which US state did the first battle of the Civil War take place?",
    41 : "Which midwestern US state contains Mount Rushmore?",
    42 : "In which southeastern US state did bluegrass music and Jack Daniels originate from?",
    43 : "Which southern state is also known as the Lone Star State?",
    44 : "Which Four Corners state contains the Great Salt Lake?",
    45 : "Which northeastern US state has been previously claimed by both New Hampshire and New York?",
    46 : "Which US state holds the largest military base in the country?",
    47 : "Which northwest US state is home to the first revolving restaurant in the country?",
    48 : "Which state located in the Appalachian region was admitted into the United States during the American Civil War?",
    49 : "Which midwest US state is known as the dairy capital of the United States?",
    50 : "Which US state was the first state to give women the right to vote?",
    51 : "What color were the Witch of the East's slippers in the original Wizard of Oz?",
    52 : "In Star Wars, what is the Emporers last name?",
    53 : "What is the name of the Queen witch in Sleeping Beauty?",
    54 : "Which Disney film has a main character that doesn't speak?",
    55 : "What was the first Disney film to be nominated for an Oscar?",
    56 : "In Aladdin, what animal does Jafar turn into?",
    57 : "Which Disney princess has healing powers?",
    58 : "Which Disney princess is also known as 'The Fairest One of All?'",
    59 : "What is the name of the teacup in 'Beauty and the Beast'?",
    60 : "What is the name of the antagonist in 'The Emperor's New Groove'?",
    61 : "In 'The Little Mermaid,' what is the name of Ariel's father?",
    62 : "In 'The Emperor's New Groove,' what animal does Kuzco turn into?",
    63 : "In 'Cars,' what is Lightning McQueen's racing numbers?",
    64 : "What is the name of the antagonist in 'Toy Story 2'?",
    65 : "How any animal main characters are there in 'Winnie the Pooh'?",
    66 : "What is the name of the tree that attacks Harry and Ron in 'Harry Potter and the Chamber of Secrets'?",
    67 : "Who is the first to tell Harry Potter that he is a wizard?",
    68 : "In the Harry Potter universe, what is the name of the plant that screams when harvested?",
    69 : "Where did Harry Potter live before his parents died?",
    70 : "What is the shape of Harry Potter's patronus?"
}

TRIVIA_ANSWERS_LIST = {
    1 : "Alabama",
    2 : "Alaska",
    3 : "Arizona",
    4 : "Arkansas",
    5 : "California",
    6 : "Colorado",
    7 : "Connecticut",
    8 : "Delaware",
    9 : "Florida",
    10: "Georgia",
    11 : "Hawaii",
    12 : "Idaho",
    13 : "Illinois",
    14 : "Indiana",
    15 : "Iowa",
    16 : "Kansas",
    17 : "Kentucky",
    18 : "Louisiana",
    19 : "Maine",
    20 : "Maryland",
    21 : "Massachusetts",
    22 : "Michigan",
    23 : "Minnesota",
    24 : "Mississippi",
    25 : "Missouri",
    26 : "Montana",
    27 : "Nebraska",
    28 : "Nevada",
    29 : "New Hampshire",
    30 : "New Jersey",
    31 : "New Mexico",
    32 : "New York",
    33 : "North Carolina",
    34 : "North Dakota",
    35 : "Ohio",
    36 : "Oklahoma",
    37 : "Oregon",
    38 : "Pennsylvania",
    39 : "Rhode Island",
    40 : "South Carolina",
    41 : "South Dakota",
    42 : "Tennessee",
    43 : "Texas",
    44 : "Utah",
    45 : "Vermont",
    46 : "Virginia",
    47 : "Washington",
    48 : "West Virginia",
    49 : "Wisconsin",
    50 : "Wyoming",
    51 : "Silver",
    52 : "Palpatine",
    53 : "Maleficient",
    54 : "Dumbo",
    55 : "Beauty and the Beast",
    56 : "Cobra",
    57 : "Rapunzel",
    58 : "Snow White",
    59 : "Chip",
    60 : "Yzma",
    61 : "King Triton",
    62 : "Llama",
    63 : "95",
    64 : "Stinky Pete",
    65 : "8",
    66 : "The Whomping Willow",
    67 : "Hagrid",
    68 : "Mandrake",
    69 : "Godric's Hallow",
    70 : "Stag"    
}

CODE_GOLF_QUESTIONS_LIST = {
    "1" : "Write a function to multiply a number by 10",
    "2" : "Write a function to multiply a number by 5",
    "3" : "Write a single line of Python code that will return a newline character.",
    "4" : "Write a line of Python code which will add 10 to a number.",
    "5" : "Join a list of strings into a single string, with each string separated from the next in the list by a single space character.",
    "6" : "Create a list which is equal to the first 5 elements of the input list.",
    "7" : "Write a boolean expression that tests whether a variable containing a python string has a vowel.",
    "8" : "Write Python code which, when executed, changes a string with lowercase letters so that it's now uppercase and in reversed order."
}

CODE_GOLF_ANSWERS_LIST = {
    "1" : {"inputs": [0, 1, 2, 10], "outputs": [0, 10, 20, 100]},
    "2" : {"inputs": [0, 1, 2, 10], "outputs": [0, 5, 10, 50]},
    "3" : {"inputs": ['', '', '', ''], "outputs": ['\n', '\n', '\n', '\n']},
    "4" : {"inputs": [0, 1, 2, 10], "outputs": [10, 11, 12, 20]},
    "5" : {"inputs": [['a', 'b', 'c'], ['a b c'],[]], "outputs": ['a b c', 'a b c', '']},
    "6" : {"inputs": [[0, 1, 2, 3, 4, 5, 6]], "outputs": [[0, 1, 2, 3, 4]]},
    "7" : {"inputs": ['"ab"', '"ef"', '"ig"', '"op"', '"uv"', '"bfgpv"','""'], "outputs": [True, True, True, True, True, False, False]},
    "8" : {"inputs": ['""', '"a"', '"abc"'], "outputs": ['', 'A', 'CBA']}
}

USER_TO_PASS_LIST = {
    "Robert" : "robert",
    "Advith" : "advith",
    "Anne"   : "anne",
    "Chen"   : "chen"
}

COMMON_WORD_LIST_NOUN = ["dog", "cat", "frog", "pizza", "pie", "bed"]
COMMON_WORD_LIST_VERB = ["eat", "slap", "hug", "watch"]
COMMON_NUMBER_LIST = ["1", "2", "3", "4", "5"]
